---
- name: pretasks
  hosts: all
  remote_user: root
  gather_facts: true
  tasks:
    - name: install python
      raw: apt-get install python-minimal aptitude -y

- name: nginx servers
  hosts: cock
  remote_user: root
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present